### ISSUE TITLE
class WorkItem setResolution does not work on the latest version 

### ISSUE THREAD

**Issue by TsutomuInoue** [jesper-raemaekers/python-polarion#27]
Hello,

The setResolution method of WorkItem  class does not work on the latest version 0.1.15.

The error message says as follows:

Traceback (most recent call last):
  File "polarionCLI.py", line 126, in <module>
    workitem.setResolution(project_resolutions[toSetResolution])
  File "C:\Users\tsuto\Documents\Polarion\polarion_cli\lib\site-packages\polarion\workitem.py", line 312, in setResolution
    self.resolution.id = resolution
AttributeError: 'dict' object has no attribute 'id'

I confirmed this method does work on version 0.1.2.  
        
Could you please look into it?

Best regards,
Tsutomu Inoue

**Comment by jesper-raemaekers** [comment]
Thank you for reporting it, it will be fixed in the next released version
